### PR TITLE
Remove inla dependency and fix documentation issues

### PR DESCRIPTION
**Pull request by ericward-noaa**
## **What was changed/addressed**
Removed INLA, fixed existing documentation / export / import / linkage problems

<Short summary goes here.>

## **Related to issue(s)**
https://github.com/pfmc-assessments/indexwc/issues/37

### CODE REVIEW

**Comment by iantaylor-NOAA** [comment]
Thanks for the lightning-quick response to this problem. I also had issues installing INLA just now that were independent from the problems that @okenk had, so good for us all to have that dependency removed.

@chantelwetzel-noaa and @kellijohnson-NOAA, do either of you have time to look at this or should we just trust that @ericward-noaa knows what he's doing and doesn't require further review?

**Comment by kellijohnson-NOAA** [comment]
All of the changes look like they are a step in the right direction. I had originally not exported a lot of functions because I did not want them exposed to the user but @ericward-noaa is a user and probably sees a need for them to be exported so that is fine as well. Thank you @ericward-noaa for also doing all of the documentation. It does look like `devtools::document()` still needs to be run because there are no GitHub actions in this repo.
This will Close #38

**Review by kellijohnson-NOAA — APPROVED** [review]
See other comment but I am approving this pending `devtools::document()`

**Comment by ericward-noaa** [comment]
I'd run devtools::document() already, and had generated 2 .Rd files (I missed a third and just pushed it). I'm confused what you meant about the Github actions? 

I'm also curious how you're checking code / package builds? I had to export the functions because if I run devtools::check() or rcmdcheck::rcmdcheck() , and functions are not exported (such as format_strata), I get errors

**Comment by kellijohnson-NOAA** [comment]
Thanks @ericward-noaa and I probably was not running any checks at all. So, anything you are doing now is great! I think I typically just loaded this package using `load_all()` which does not check for exported functions.

**Pull request merged**
